### ISSUE TITLE
Tutors are sorted by when they made their account, not name or subject

### ISSUE THREAD

**Issue by EFBeuken** [StudCee/tutoring#10]
**Note: for support questions, please mail tutoring.svcover.nl**. This repository's
issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note
    at the top of this template.

* **What is the current behavior?**
When a tutor makes their account, they are added to the bottom of the list of tutors. The tutors are organised based on when they made their account, oldest being at the top

* **If the current behavior is a bug, please provide the steps to reproduce**
Make a tutoring account
Watch as you appear at the bottom of the list

* **What is the expected behavior?**
Tutors should be sorted say alphabetically or by subject. It would be nice if the user can choose what order they appear in.

* **What is the motivation / use case for changing the behavior?**
Guus doesn't always have to be first

* **Please tell us about your environment:**

  - Browser: [all | Chrome XX]

* **Other information** (e.g. detailed explanation, stacktraces, related issues,
  suggestions how to fix, links for us to have context, eg. stackoverflow,
gitter, etc)
This was on StudCees trello card of errors

**Comment by rmellema** [comment]
Commit 132ddb7c6081340d5cbd7c4ed9f9f025cc270f88 shuffles all the tutors, so this now is less of a problem, but a better sorting might be possible.

**Comment by GuusK** [comment]
So what would be the preferred way of sorting then? A static order might not be the best, since users tend to be lazy and not scroll down a lot and/or read descriptions written by tutors, thus favoring the ones on top. Since there are currently no metrics to indicate if someone is a good tutor (which might be an interesting feature) I think random order might be best.

**Comment by rmellema** [comment]
No clue what the preferred order should be. Maybe random order is best to give all of the tutors an equal chance to be selected.

**Comment by NicoStegeman** [comment]
The order is has been random for a while
