### ISSUE TITLE
Tutoring mail digest uses plural even if there is only one message thread

### ISSUE THREAD

**Issue by EFBeuken** [StudCee/tutoring#11]
**Note: for support questions, please mail tutoring.svcover.nl**. This repository's
issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note
    at the top of this template.

* **What is the current behavior?**
When the mail digest goes out and there's only one message thread, it says that you have "1 ongoing conservations" owtte

* **If the current behavior is a bug, please provide the steps to reproduce**
Get someone to send you a message
Make sure nobody else sends you a message
Don't read it
Get a digest saying you have "1 ongoing conservations" owtte

* **What is the expected behavior?**
That the digest can do the singular case

* **What is the motivation / use case for changing the behavior?**
The tutoring system should have some knowledge about grammar

* **Please tell us about your environment:**

  - Browser: [all | Chrome XX  ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues,
  suggestions how to fix, links for us to have context, eg. stackoverflow,
gitter, etc)
From the StudCee bug trello

**Comment by NicoStegeman** [comment]
Added singular to the word conversations and to unread messages
