### ISSUE TITLE
When already connected to Telegram there's a button that says "Connect to Telegram"

### ISSUE THREAD

**Issue by EFBeuken** [StudCee/tutoring#2]
**Note: for support questions, please mail tutoring.svcover.nl**. This repository's
issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note
    at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
report a bug

* **What is the current behavior?**
When already connected to Telegram there's a button that says "Connect to Telegram"

* **If the current behavior is a bug, please provide the steps to reproduce**
connect to telegram
go back to the tutoring system
observe that the option "connect to telegram" is still available

* **What is the expected behavior?**
that it doesn't say "connect to telegram"

* **What is the motivation / use case for changing the behavior?**
it is unexpected

* **Please tell us about your environment:**

  - Version: 2.0.0-beta.X ???
  - Browser: [Chrome XX  ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart] ???????

* **Other information** (e.g. detailed explanation, stacktraces, related issues,
  suggestions how to fix, links for us to have context, eg. stackoverflow,
gitter, etc)
This is from the trello list of issues studcee has already found

**Comment by NicoStegeman** [comment]
When telegram_chat_id is not None for a user the telegram bot promo is not rendered anymore.
