### ISSUE TITLE
If user is removed from Cover, they remain in CACTuS. User can still send and receive messages/emails.

### ISSUE THREAD

**Issue by EFBeuken** [StudCee/tutoring#4]
**Note: for support questions, please mail tutoring.svcover.nl**. This repository's
issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note
    at the top of this template.

* **What is the current behavior?**
If users get kicked out of cover, they stay in the tutoring system. People can still send them messages and they still receive emails.

* **If the current behavior is a bug, please provide the steps to reproduce**
This is a bug found by studcee. It can be reproduced by setting a person in the database to "is banned" then trying to send a message.

* **What is the expected behavior?**
Banned users shouldn't be allowed to log into the system. They should also get a notification saying that they are no longer on the Cover system => cannot use CACTuS

* **What is the motivation / use case for changing the behavior?**
Non-Cover members aren't allowed to use the system as Cover's member database is used to verify a person on CACTuS

* **Please tell us about your environment:**

  - Browser: [all | Chrome XX ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues,
  suggestions how to fix, links for us to have context, eg. stackoverflow,
gitter, etc)
This was listed on StudCee's trello list of things

**Comment by NicoStegeman** [comment]
If you are not a member anymore (uses the member_till field from the cover api) you will be flagged as inactive and cannot use the website anymore. Also your requests and offer will not be listed anymore.

**Comment by NicoStegeman** [comment]
Also create member update command that updates all member entries in the database.
