### ISSUE TITLE
If two anonymous people talk to each other, their icons and names are indistinguishable.

### ISSUE THREAD

**Issue by EFBeuken** [StudCee/tutoring#5]
**Note: for support questions, please mail tutoring.svcover.nl**. This repository's
issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note
    at the top of this template.

* **What is the current behavior?**
If two anonymous people talk to each other, their icons and names are indistinguishable. It can be difficult to keep track of who is saying what

* **If the current behavior is a bug, please provide the steps to reproduce**
Two people talk anonymously to each other on CACTuS

* **What is the expected behavior?**
It would be better to be able to distinguish the two users by using different coloured icons or names (I think different coloured icons should be enough)

* **What is the motivation / use case for changing the behavior?**
This will help to distinguish the two users who are talking anonymously

* **Please tell us about your environment:**

  - Browser: [all | Chrome XX ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues,
  suggestions how to fix, links for us to have context, eg. stackoverflow,
gitter, etc)
This bug was first reported on studcee's trello of bugs

**Comment by NicoStegeman** [comment]
The website will render your own name or refer to you as you if you are anonymous. Only other user appear as anonymous now.
