### ISSUE TITLE
Users can start multiple conversations on the same request/offer.

### ISSUE THREAD

**Issue by EFBeuken** [StudCee/tutoring#7]
**Note: for support questions, please mail tutoring.svcover.nl**. This repository's
issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note
    at the top of this template.

* **What is the current behavior?**
Users can start multiple conversations by clicking on a request/offer of tutoring multiple times

* **If the current behavior is a bug, please provide the steps to reproduce**
> Start a conversation with a person by clicking on their request for tutoring
> Go back to the page with their tutoring request
> Start another conversation with that same person by again clicking on the tutoring request
> Go back to the page with their tutoring request
> Repeat for someone offering tutoring

* **What is the expected behavior?**
If the user tries to start another conversation and the same request, they should either be directed to the conversation they already started or be prevented from starting the conservation. The same should be applied to offers of tutoring.

Note that this isn't about having multiple conversations with the same person. This should be allowed as the person may want help with different subjects. This is specifically about creating multiple conversations from one tutoring request/offer of tutoring

* **What is the motivation / use case for changing the behavior?**
Multiple conversations can be annoying. Don't want to clog up the system too much.

* **Please tell us about your environment:**

  - Browser: [all | Chrome XX ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues,
  suggestions how to fix, links for us to have context, eg. stackoverflow,
gitter, etc)
This came from the trello list of issues that StudCee has found

**Comment by NicoStegeman** [comment]
Conversations are attached to requests if created trough them. I decided not to link offers and conversations, because a user should be able to open multiple conversation with the same offer. For example when you want tutoring for a different course.
